### PR TITLE
Adds CF grid mapping detection to get CRS information from netCDF input

### PR DESCRIPTION
**Pull request by JamesVarndell**

### CODE REVIEW

**Comment by sandorkertesz** [comment]
Is this something that could be used for GRIB data too?

**Comment by JamesVarndell** [comment]
> Is this something that could be used for GRIB data too?

Not directly, as this feature is specifically focused on understanding CF-compliant metadata. However, I have an open issue to develop something similar for GRIB.

**Comment by JamesVarndell** [comment]
I have added a test skip for anything cartopy-related, so that if cartopy is not installed, the test will not run.

**Comment by sandorkertesz** [comment]
Please can you change the target to the "develop" branch?

**Pull request closed without merging**
