### PR TITLE
Translators and Wrappers

### PR DESCRIPTION
**Pull request by EddyCMWF**
Here is a start to some translators and wrappers.
Maybe it should be merged into another branch so others can work on it, but I don't current;y have write permissions on the main repo

### CODE REVIEW

**Comment by sandorkertesz** [comment]
@EddyCMWF, great work. It would be really useful to add notebook examples for the two new methods "from_object" and "transform".

**Comment by sandorkertesz** [comment]
Not sure why the unit-tests and other tests are skipped.

**Comment by sandorkertesz** [comment]
Maybe it should be merged into "develop"?  Has been introduced this week.

**Comment by sandorkertesz** [comment]
Thanks for the notebook! The only thing missing is to add tests for the "from_object" and "transform" methods.

**Comment by EddyCMWF** [comment]
Hi Sandor,
I added a from_object notebook, it's not the most interesting, but it can evolve as we add more features to the Wrapper classes.
Eddy

**Comment by EddyCMWF** [comment]
> Thanks for the notebook! The only thing missing is to add tests for the "from_object" and "transform" methods.

Tests added.
In the end, the from_object tests are the same as the get_wrapper tests that were already there, funnily enough, from_object is a wrapper to get_wrapper

**Comment by sandorkertesz** [comment]
Please can you change the target to "develop" branch?

**Comment by sandorkertesz** [comment]
Thanks! When the conflicts are sorted out it can be merged into develop.

**Comment by EddyCMWF** [comment]
Hmmm, it seemed this was closed without merging when the develop branch was deleted. I will re-open and see if I can fix the conflicts

**Pull request merged**
